### ISSUE TITLE
Add a search for emojis based on their short name

### ISSUE THREAD

**Issue by ghost** [abourtnik/emojis-world#1]
I want to transform things (e.g: `:smile:` to 😄), discord like. I saw that you api returns a `name` in the response. Maybe you could use it to transform into an emoji. What do you think ?

**Comment by abourtnik** [comment]
Hello, I'm not completely understand your issue.

You suggest me to create a new endpoint which transform on word to a unique emoji ?

For exemple like this : https://api.emojisworld.io/v1/transform?q=:smile:

Return

`{
"id": 6,
"name": "grinning face with smiling eyes",
"emoji": "😄",
"unicode": "1F604",
"score": 0,
"category": {
"id": 1,
"name": "Smileys & People"
},
"sub_category": {
"id": 1,
"name": "face-positive"
},
"childrens": []
}`

**Comment by ghost** [comment]
Exactly, what do you think about that? I could submit a PR.

**Comment by abourtnik** [comment]
Yes it's a good idea. I wait for your PR :)
