### ISSUE TITLE
How do I contribute emoji?

### ISSUE THREAD

**Issue by isPoto** [abourtnik/emojis-world#5]
I want to move other open source Emoji to this repository, can I do that? I want to expand the number of emoji

**Comment by abourtnik** [comment]
Hello @isPoto,

You can send me a json or database export in this issue or by email to contact@antonbourtnik.fr

I integrate your emojis in production database.

This informations are required : 

- name (ex : grinning cat face)
- emoji (ex : 😸 )
- unicode (ex: 1F638)
